### ISSUE TITLE
Broken indirect dependency on Murmur3

### ISSUE THREAD

**Issue by vito** [elm-explorations/benchmark#21]
👋 Just dropping a note that this package has become unusable due to a broken indirect dependency: https://github.com/robinheghan/murmur3/issues/5

It looks like the dependency is being pulled in because of [`mdgriffith/style-elements`](https://github.com/mdgriffith/style-elements/blob/eeec6c095b792543db04751c9b81bce9652bd11a/elm.json#L26). Maybe this could/should be resolved by switching to `mdgriffith/elm-ui` which is its successor, and no longer depends on `murmur3`?

(I'm sure that's more work it sounds though.)

**Comment by BrianHicks** [comment]
I see a couple options:

1. @mdgriffith, would you be interested in taking this repo over since you're doing a lot of stuff with optimizations now? The outdated dep might not be a problem because of…
2. I think Robin may re-publish murmur3 under his old account… that may make this just go away!
3. Remove the UI, or make it much uglier. That seems kind of fine, TBQH? Most of this could probably be accomplished with inline styles so it didn't have to be dependent on more than `elm/html`.

**Comment by BrianHicks** [comment]
also, y'all are using this in Concourse stuff? Cool!

**Comment by robinheghan** [comment]
I've now re-published `murmur3` as `robinheghan/murmur3 v1.0.0`.

**Comment by altaywtf** [comment]
it's also used in the _Write Fast Applications_ section of @jfairbank's [Programming Elm](https://programming-elm.com) book 😇

**Comment by vito** [comment]
> also, y'all are using this in Concourse stuff? Cool!

Yep! We use it for [benchmarking the build page rendering speed](https://github.com/concourse/concourse/tree/master/web/elm/benchmarks), since it's performance critical and regressions are easy to accidentally introduce.

(In case you weren't already aware, Concourse's entire UI, save for the pipeline visualization, is written in Elm.)

**Comment by mdgriffith** [comment]
Hello!  Just released a patch for style-elements.  Thanks @BrianHicks  unfortunately I think I probably already have too much on my plate 😅

**Comment by BrianHicks** [comment]
I think this is fixed in 1.0.2. Would someone try it out and let me know if you have any more problems?
